In [1]:
import numpy as np

# Numpy attributes

1. dimension, diguakan untuk melihat dimensi yang dimiliki suatu numpy array
2. shape, digunakan untuk mengetahui berapa jumlah baris dan kolom dari suatu numpy array
3. type, digunakan untuk mengetahui tipe data yang dimiliki suatu numpy array
4. itemsize, untuk melihat ukuran memori yang dibutuhkan untuk menyimpan sebuah numpy array
5. nbytes, digunakan untuk menghitung total bytes yang dimiliki suatu numpy array

In [40]:
arr = [[1,2,3,4],[4,5,6,7]]
arr_1 = [2,1,4,5]
arr_1_num = np.array([arr_1])
arr_num = np.array(arr)
print(arr_1_num)
print("")
print(arr_num)

[[2 1 4 5]]

[[1 2 3 4]
 [4 5 6 7]]


In [5]:
print(arr)

[[1, 2, 3, 4], [4, 5, 6, 7]]


In [6]:
print(type(arr_num))

<class 'numpy.ndarray'>


In [7]:
# dimension
arr_num.ndim

2

In [42]:
# shape
print(arr_num.shape)
print(arr_1_num.shape)

(2, 4)
(1, 4)


In [10]:
# type
arr_num.dtype

dtype('int32')

In [11]:
# itemsize
arr_num.itemsize

4

In [12]:
# nbytes
arr_num.nbytes

32

# Indexing Arrays

In [14]:
print(arr_num)
arr_num[1][2:]

[[1 2 3 4]
 [4 5 6 7]]


array([6, 7])





### Slicing Array






In [15]:
arr_slice = np.array(range(10))
print(arr_slice)

#[start:stop:step]
arr_slice[0:7:2]

[0 1 2 3 4 5 6 7 8 9]


array([0, 2, 4, 6])

In [24]:
# multidimension
arr_multi = [[1,2,3,5],[2,3,4,5],[7,8,9,6]]
arr_multi_np = np.array(arr_multi)
print(arr_multi_np)
print(" ")
print(arr_multi_np[1:,2:])

[[1 2 3 5]
 [2 3 4 5]
 [7 8 9 6]]
 
[[4 5]
 [9 6]]


# Reshaping Array ( jumlah baris dan kolom harus sama )

In [75]:
# nama_objek.reshape(baris,kolom)\

arr_multi_np.reshape(3,4)

array([[1, 2, 3, 5],
       [2, 3, 4, 5],
       [7, 8, 9, 6]])

### Joining Array

In [37]:
arr_num_2 = np.array([[4,5,2,1],[7,8,9,3]])
arr_num_3 = np.array([[22,33,44,11],[55,66,77,88]])
arr_num_4 = np.array([[12,23,34,45],[65,54,43,21],[78,6,98,10]])

In [35]:
array_join = np.concatenate([arr_num_4,arr_num_2])
print(array_join)

[[12 23 34 45]
 [65 54 43 21]
 [78  6 98 10]
 [ 4  5  2  1]
 [ 7  8  9  3]]


# Objek Pandas:Series vs DataFrame

Series dan Dataframe ini adalah suatu objek tempat kita menyimpan data secara terstruktur. Perbedaan dari Series dan DataFrame ini terletak pada strukturnya dan juga attribute dan method-method yang mereka miliki, untuk perbedaan strukturnya adalah sebagai berikut :

1. Series adalah objek 1 dimensi
2. DataFrame adalah suatu objek 2 dimensi, mirip seperti tabel



### Series

Series memiliki persamaan dengan list yaitu dapat dilakukan metode slicing, yaitu mengakses/indexing pada object series tersebut (yang akan dipelajari di hari ke-2). Juga series memiliki persamaan dengan dictionary yaitu index yang dimiliki series berguna seperti keys pada dictionary.

In [43]:
import pandas as pd

In [46]:
x = pd.Series([1,2,3,4],index=["satu","dua","tiga","empat"])
print(x)

satu     1
dua      2
tiga     3
empat    4
dtype: int64


In [47]:
x["satu"]

1

In [49]:
x.index = [1,2,3,4]

In [50]:
print(x)

1    1
2    2
3    3
4    4
dtype: int64


### DataFrame

dataframe berupa dictionary

In [58]:
arr_dict = {
    "nama" : ["bayu","resky","andhika"],
    "umur" : [23,32,45]
}

In [59]:
dataFrame_arr_dict = pd.DataFrame(arr_dict)

In [60]:
print(dataFrame_arr_dict)

      nama  umur
0     bayu    23
1    resky    32
2  andhika    45


In [61]:
dataFrame_arr_dict["nama"]

0       bayu
1      resky
2    andhika
Name: nama, dtype: object

In [65]:
dataFrame_arr_dict["nama"][0]

'bayu'

In [70]:
for i in dataFrame_arr_dict.nama[0]:
    print(i)

b
a
y
u


In [71]:
for i in dataFrame_arr_dict.nama:
    print(i)

bayu
resky
andhika


In [72]:
print(dataFrame_arr_dict.loc[1])

nama    resky
umur       32
Name: 1, dtype: object
